export const qsThemes = {
  neo_brutalism: {
    appBg: "bg-[var(--qs-bg,#F4F4F0)]",
    textMain: "text-[var(--qs-text,#000000)]",
    textSub: "text-slate-800",
    header: "bg-[var(--qs-bg,#F4F4F0)] border-b-4 border-[var(--qs-text,#000000)]",
    searchWrap: "bg-[var(--qs-card-bg,#ffffff)] border-4 border-[var(--qs-text,#000000)] shadow-[4px_4px_0_0_var(--qs-text,#000000)] focus-within:shadow-[6px_6px_0_0_var(--qs-text,#000000)] rounded-none",
    searchInput: "bg-transparent text-[var(--qs-text,#000000)] placeholder:text-slate-500 font-bold",
    pillActive: "bg-[var(--qs-primary,#ea580c)] text-white border-4 border-[var(--qs-text,#000000)] shadow-[4px_4px_0_0_var(--qs-text,#000000)] rounded-none font-black",
    pillInactive: "bg-[var(--qs-card-bg,#ffffff)] text-[var(--qs-text,#000000)] border-4 border-[var(--qs-text,#000000)] shadow-[4px_4px_0_0_var(--qs-text,#000000)] rounded-none font-bold hover:-translate-y-1 hover:shadow-[6px_6px_0_0_var(--qs-text,#000000)]",
    card: "bg-[var(--qs-card-bg,#ffffff)] border-4 border-[var(--qs-text,#000000)] rounded-none shadow-[6px_6px_0_0_var(--qs-text,#000000)] hover:-translate-y-1 hover:shadow-[8px_8px_0_0_var(--qs-text,#000000)]",
    imgWrap: "border-r-4 border-[var(--qs-text,#000000)] bg-[var(--qs-bg,#F4F4F0)] rounded-none",
    btnPrimary: "bg-[var(--qs-primary,#ea580c)] text-white border-4 border-[var(--qs-text,#000000)] shadow-[4px_4px_0_0_var(--qs-text,#000000)] rounded-none font-black uppercase hover:-translate-y-1 hover:shadow-[6px_6px_0_0_var(--qs-text,#000000)]",
    btnAction: "bg-[var(--qs-text,#000000)] text-white border-4 border-[var(--qs-text,#000000)] rounded-none",
    qtyControl: "bg-[var(--qs-card-bg,#ffffff)] border-4 border-[var(--qs-text,#000000)] shadow-[4px_4px_0_0_var(--qs-text,#000000)] rounded-none",
    qtyBtn: "bg-[var(--qs-card-bg,#ffffff)] text-[var(--qs-text,#000000)] hover:bg-slate-200",
    cartPopup: "bg-[var(--qs-primary,#ea580c)] text-white border-4 border-[var(--qs-text,#000000)] shadow-[8px_8px_0_0_var(--qs-text,#000000)] rounded-none",
    modal: "bg-[var(--qs-bg,#F4F4F0)] border-4 border-[var(--qs-text,#000000)] rounded-none",
    modalHeader: "bg-[var(--qs-card-bg,#ffffff)] border-4 border-[var(--qs-text,#000000)] shadow-[4px_4px_0_0_var(--qs-text,#000000)] rounded-none",
    methodCard: "bg-[var(--qs-card-bg,#ffffff)] border-4 border-[var(--qs-text,#000000)] shadow-[4px_4px_0_0_var(--qs-text,#000000)] rounded-none hover:-translate-y-1 hover:shadow-[6px_6px_0_0_var(--qs-text,#000000)]",
    methodActive: "bg-[var(--qs-primary,#ea580c)] text-white border-4 border-[var(--qs-text,#000000)] shadow-[4px_4px_0_0_var(--qs-text,#000000)] rounded-none scale-[1.02]",
  },
  y2k: {
    appBg: "bg-[var(--qs-bg,#fdf4ff)]",
    textMain: "text-[var(--qs-text,#1e293b)]",
    textSub: "text-slate-500",
    header: "bg-white/40 backdrop-blur-2xl border-b border-white/60",
    searchWrap: "bg-[var(--qs-card-bg,#ffffff80)] border border-white/80 rounded-full shadow-inner focus-within:ring-2 focus-within:ring-[var(--qs-primary,#d946ef)]",
    searchInput: "bg-transparent text-[var(--qs-text,#1e293b)] placeholder:text-slate-400 font-medium",
    pillActive: "bg-[var(--qs-primary,#d946ef)] text-white rounded-full shadow-[0_4px_20px_var(--qs-primary,#d946ef)] font-bold",
    pillInactive: "bg-[var(--qs-card-bg,#ffffff80)] text-slate-600 border border-white/80 rounded-full font-medium hover:bg-white/80 backdrop-blur-sm",
    card: "bg-[var(--qs-card-bg,#ffffff99)] backdrop-blur-xl border border-white/80 rounded-[2rem] shadow-[0_8px_32px_rgba(255,255,255,0.4)] hover:shadow-[0_12px_40px_rgba(255,255,255,0.6)] hover:-translate-y-1",
    imgWrap: "rounded-2xl border-2 border-white/60 bg-white/50",
    btnPrimary: "bg-[var(--qs-primary,#d946ef)] text-white rounded-full shadow-[0_8px_20px_var(--qs-primary,#d946ef)] font-bold hover:scale-105",
    btnAction: "bg-[var(--qs-primary,#d946ef)] text-white rounded-xl shadow-md",
    qtyControl: "bg-[var(--qs-card-bg,#ffffff99)] border border-white/80 rounded-2xl shadow-inner backdrop-blur-sm",
    qtyBtn: "bg-white/80 text-slate-700 hover:bg-white rounded-xl",
    cartPopup: "bg-[var(--qs-primary,#d946ef)] text-white rounded-[2rem] shadow-[0_20px_40px_var(--qs-primary,#d946ef)] backdrop-blur-xl",
    modal: "bg-white/80 backdrop-blur-3xl rounded-t-[3rem] border-t border-white",
    modalHeader: "bg-[var(--qs-card-bg,#ffffff99)] border border-white/80 rounded-2xl",
    methodCard: "bg-[var(--qs-card-bg,#ffffff80)] border border-white/80 rounded-2xl backdrop-blur-md hover:bg-white/80",
    methodActive: "bg-[var(--qs-primary,#d946ef)] text-white border-[var(--qs-primary,#d946ef)] shadow-[0_4px_20px_var(--qs-primary,#d946ef)] rounded-2xl",
  },
  streetwear: {
    appBg: "bg-[var(--qs-bg,#fafafa)]",
    textMain: "text-[var(--qs-text,#18181b)] tracking-tighter",
    textSub: "text-zinc-500",
    header: "bg-[var(--qs-bg,#fafafa)] border-b border-zinc-200",
    searchWrap: "bg-[var(--qs-card-bg,#f4f4f5)] rounded-none border-none focus-within:ring-2 focus-within:ring-[var(--qs-text,#18181b)]",
    searchInput: "bg-transparent text-[var(--qs-text,#18181b)] placeholder:text-zinc-400 font-medium",
    pillActive: "bg-[var(--qs-text,#18181b)] text-[var(--qs-bg,#fafafa)] rounded-none font-bold uppercase tracking-widest text-xs",
    pillInactive: "bg-[var(--qs-card-bg,#f4f4f5)] text-zinc-600 rounded-none font-medium uppercase tracking-widest text-xs hover:bg-zinc-200",
    card: "bg-[var(--qs-card-bg,#ffffff)] border border-zinc-200 rounded-none shadow-sm hover:shadow-xl hover:-translate-y-1",
    imgWrap: "rounded-none bg-[var(--qs-card-bg,#f4f4f5)]",
    btnPrimary: "bg-[var(--qs-primary,#ea580c)] text-white rounded-none font-black uppercase tracking-widest shadow-lg hover:opacity-90",
    btnAction: "bg-[var(--qs-text,#18181b)] text-[var(--qs-bg,#fafafa)] rounded-none",
    qtyControl: "bg-[var(--qs-card-bg,#f4f4f5)] rounded-none border border-zinc-200",
    qtyBtn: "bg-zinc-200 text-[var(--qs-text,#18181b)] hover:bg-zinc-300 rounded-none",
    cartPopup: "bg-[var(--qs-text,#18181b)] text-[var(--qs-bg,#fafafa)] rounded-none shadow-2xl",
    modal: "bg-[var(--qs-card-bg,#ffffff)] rounded-none border-t border-zinc-200",
    modalHeader: "bg-[var(--qs-bg,#fafafa)] border border-zinc-200 rounded-none",
    methodCard: "bg-[var(--qs-bg,#fafafa)] border border-zinc-200 rounded-none hover:bg-zinc-100",
    methodActive: "bg-[var(--qs-text,#18181b)] text-[var(--qs-bg,#fafafa)] border-[var(--qs-text,#18181b)] rounded-none",
  },
  playful: {
    appBg: "bg-[var(--qs-bg,#FFF9F0)]",
    textMain: "text-[var(--qs-text,#1e293b)]",
    textSub: "text-amber-600/80",
    header: "bg-[var(--qs-bg,#FFF9F0)]/90 backdrop-blur-md",
    searchWrap: "bg-[var(--qs-card-bg,#fffbeb)] border-2 border-amber-100 rounded-full focus-within:ring-4 focus-within:ring-amber-200 focus-within:border-amber-400",
    searchInput: "bg-transparent text-amber-900 placeholder:text-amber-400 font-bold",
    pillActive: "bg-[var(--qs-primary,#fbbf24)] text-amber-950 rounded-full font-black shadow-[0_4px_15px_rgba(251,191,36,0.4)]",
    pillInactive: "bg-[var(--qs-card-bg,#ffffff)] text-amber-600 border-2 border-amber-100 rounded-full font-bold hover:bg-amber-50",
    card: "bg-[var(--qs-card-bg,#ffffff)] border-2 border-amber-100 rounded-[2.5rem] shadow-[0_8px_30px_rgba(251,191,36,0.15)] hover:shadow-[0_12px_40px_rgba(251,191,36,0.25)] hover:-translate-y-1",
    imgWrap: "rounded-[2rem] border-2 border-amber-50 bg-[var(--qs-card-bg,#fffbeb)]",
    btnPrimary: "bg-[var(--qs-primary,#fb923c)] text-white rounded-full font-black shadow-[0_8px_20px_rgba(251,146,60,0.3)] hover:scale-105",
    btnAction: "bg-amber-100 text-amber-700 rounded-full font-bold",
    qtyControl: "bg-[var(--qs-card-bg,#fffbeb)] border-2 border-amber-100 rounded-[1.5rem]",
    qtyBtn: "bg-[var(--qs-card-bg,#ffffff)] text-amber-700 hover:bg-amber-100 rounded-[1rem]",
    cartPopup: "bg-[var(--qs-primary,#ea580c)] text-white rounded-[2.5rem] shadow-[0_20px_40px_rgba(249,115,22,0.3)]",
    modal: "bg-[var(--qs-card-bg,#ffffff)] rounded-t-[3rem]",
    modalHeader: "bg-[var(--qs-card-bg,#fffbeb)] border border-amber-100 rounded-[1.5rem]",
    methodCard: "bg-[var(--qs-card-bg,#ffffff)] border-2 border-amber-100 rounded-[2rem] hover:bg-amber-50",
    methodActive: "bg-[var(--qs-primary,#fbbf24)] text-white border-amber-400 shadow-[0_4px_20px_rgba(251,191,36,0.3)] rounded-[2rem] scale-[1.02]",
  },
  bento: {
    appBg: "bg-[var(--qs-bg,#f8fafc)]",
    textMain: "text-[var(--qs-text,#0f172a)]",
    textSub: "text-slate-500",
    header: "bg-[var(--qs-bg,#ffffffcc)] backdrop-blur-xl border-b border-slate-100",
    searchWrap: "bg-[var(--qs-card-bg,#f1f5f9)] rounded-2xl border border-transparent focus-within:bg-white focus-within:border-[var(--qs-primary,#fdba74)] focus-within:ring-2 focus-within:ring-[var(--qs-primary,#f97316)]/20 shadow-sm",
    searchInput: "bg-transparent text-[var(--qs-text,#0f172a)] placeholder:text-slate-400 font-medium",
    pillActive: "bg-[var(--qs-primary,#0f172a)] text-[var(--qs-bg,#ffffff)] rounded-xl font-bold shadow-md",
    pillInactive: "bg-[var(--qs-card-bg,#ffffff)] text-slate-600 border border-slate-200 rounded-xl font-medium hover:bg-slate-50 shadow-sm",
    card: "bg-[var(--qs-card-bg,#ffffff)] border border-slate-100 rounded-3xl shadow-sm hover:shadow-md transition-shadow",
    imgWrap: "rounded-2xl bg-[var(--qs-card-bg,#f1f5f9)]",
    btnPrimary: "bg-[var(--qs-primary,#ea580c)] text-white rounded-xl font-bold shadow-sm hover:opacity-90 active:scale-95",
    btnAction: "bg-[var(--qs-card-bg,#f1f5f9)] text-slate-700 rounded-xl font-medium",
    qtyControl: "bg-[var(--qs-bg,#f8fafc)] border border-slate-200 rounded-xl",
    qtyBtn: "bg-[var(--qs-card-bg,#ffffff)] text-slate-700 border border-slate-200 hover:bg-slate-100 rounded-lg shadow-sm",
    cartPopup: "bg-[var(--qs-text,#0f172a)] text-[var(--qs-bg,#ffffff)] rounded-2xl shadow-2xl",
    modal: "bg-[var(--qs-card-bg,#ffffff)] rounded-t-3xl border-t border-slate-200",
    modalHeader: "bg-[var(--qs-bg,#f8fafc)] border border-slate-100 rounded-2xl",
    methodCard: "bg-[var(--qs-card-bg,#ffffff)] border border-slate-200 rounded-2xl shadow-sm hover:bg-slate-50",
    methodActive: "bg-[var(--qs-bg,#f8fafc)] border-[var(--qs-primary,#ea580c)] ring-1 ring-[var(--qs-primary,#ea580c)] shadow-md rounded-2xl",
  }
};
